blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Lumengrid/OritechThings/blob/main/documentation/tiered_addons/index.html
    about: Everything about Addons